name: Publish on push to master

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: npm install, build and test
        run: |
          npm install --ignore-scripts
          npm run build --if-present
          npm test
      - run: npm publish  
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


